### ISSUE TITLE
Will this work on distributions like Debian?

### ISSUE THREAD

**Issue by edjroz** [wildtruc/nvidia-prime-select#1]
What requirements would it need to work ?

**Comment by wildtruc** [comment]
Normaly, nothing. More or less.
You just have to edit library.conf to your need and copy paste it in /etc/nvidia-prime.
It wiil be probably like this:

nv_drv_32='/usr/lib/i386-linux-gnu/'
nv_drv_64='/usr/lib/x86_64-linux-gnu/'
nv_xorg_path='/uslr/lib/xorg'
rc_dir='/etc/rc.local'

Then, you're good.

Let me know if you meet any problems.
