### ISSUE TITLE
Has this been tested with Fedora 30

### ISSUE THREAD

**Issue by joeg1484** [wildtruc/nvidia-prime-select#10]
Just wondering if this was tested on Fedora 30 and if it works?

**Comment by wildtruc** [comment]
No special reason it doesn't.
Can't really tell. recent nvidia drivers and kernels, especially gcc have moved to a higher level, everything could happen.
My laptop's nvidia device is now out of date for new driver and gcc, I can't even test my self.
To be continued... :s

**Comment by MichaelKofler** [comment]
Worked for me. (I only did some small tests. I don't use Fedora regularly on this notebook with NVIDIA graphics.)

**Comment by joeg1484** [comment]
Thanks! I have to test still, but if something is not working, ill open another ticket.

**Comment by kareemadel** [comment]
I tried it on Fedora 30, I have Nvidia enabled, to begin with, it worked fine when selecting intel instead but when I try to go back to Nvidia it fails it says that it succeeded but when I reboot I don't get to the login screen. I had to go to the recovery shell and select Intel again to be able to login.

**Comment by kareemadel** [comment]
What I do for now is use the tool to enable Intel, and uninstall it when I want to enable Nvidia.

**Comment by wildtruc** [comment]
I have to upgrade de Fedora 30 shortly. I will try then on my optimus laptop, but it seems my nvidia hardware is out of date :/
Prime is more and more supported by distro's and nvidia drivers, so ... 
let's hope I find something out.

**Comment by umoqnier** [comment]
> I tried it on Fedora 30, I have Nvidia enabled, to begin with, it worked fine when selecting intel instead but when I try to go back to Nvidia it fails it says that it succeeded but when I reboot I don't get to the login screen. I had to go to the recovery shell and select Intel again to be able to login.
> 
> It's a fresh install of Fedora 30 with Gnome.

I have exactly the same issue with my GTX1050 and Fedora 30. Fresh install with gnome. Can you re-open this issue?

**Comment by wildtruc** [comment]
I have to upgrade de Fedora 30. I will try then on my optimus laptop, but it seems my nvidia hardware is out of date :/
Prime is more and more supported by distro's and nvidia drivers, so ... 
let's hope I find something out.

**Comment by Fludixx** [comment]
I had the same issue. In the xorg.conf was no BusID set, so i ran `lspci` and checked the BusID of my nvidia card.
it listed all of my devices and among them was my gpu.
`03:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 940MX] (rev a2)`
then i just edited the xorg.conf and set the BusId to PCI:3:0:0. 

After an reboot everything worked fine

**Comment by wildtruc** [comment]
oh oh ! I'll give a look on code to get a better bus id detection.
I will leave a note when done.

**Comment by wildtruc** [comment]
Script has been fixed. Hope it will work normaly now.
Feel free to report any bug.

**Comment by wildtruc** [comment]
Woops, didn't saw the "3D controller" thing in your line !
Is ' lspci | grep "VGA" ' not reporting any more?

**Comment by wildtruc** [comment]
bus IDs list regex pattern with new word added was wrong.
Please "git pull" or "make update" again.

**Comment by wildtruc** [comment]
Bad news, Grub config in fedora 30 and maybe other recent distros upgrade, has changed.
Options are not setted any more per kernel but as options default set.
Then, grub auto config is break in code.

I working on it and will push changes as soon as possible (my laptop is currently out of service).

**Comment by wildtruc** [comment]
Fixes done. Hopefully.
Waiting for your feedback.

**Comment by wildtruc** [comment]
This thread is now closed. If you meet new bugs or issues, please open a new issue topic.
