### ISSUE TITLE
Can I use NPS as kernel parameter?

### ISSUE THREAD

**Issue by Jay-Aberlour** [wildtruc/nvidia-prime-select#13]
I (Fedora 30) have the issue that my DM only shows up if a monitor is attached on a HDMI-port when NPS is set to nvidia (it functions like normal on intel). This makes booting kinda annoying. To solve this, I want to create two grub-entries: one for intel and one for nvidia. 
Is there a way to run NPS as a kernel parameter?

**Comment by wildtruc** [comment]
No, prime-select can't be set as a kernel parameter.
It sounds like the VGA ghost screen.
Try to control under Intel your xrandr UI when your HDMI screen is plugged in and look if a 3rd screen shows up. If it is, disable it (not sure it'll work, it usually appear under nvidia set).

If not, give the printing of : 
```xrandr --query```
```cat /etc/default/grub```
```cat /etc/X11/xorg.conf```
```cat /var/log/Xorg.0.log```
```lspci -mm | grep -i nvidia```
I can't do more without.

**Comment by Jay-Aberlour** [comment]
Thank you for the effort @wildtruc 
There is no way I can detect a third monitor. 
Here the ouput you asked. 

 xrandr --query
> Screen 0: minimum 8 x 8, current 3840 x 1080, maximum 32767 x 32767
HDMI-0 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 521mm x 293mm
   1920x1080     60.00*+  59.94    50.00    60.00    50.04  
   1680x1050     59.95  
   1440x900      59.89  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94    59.93  
eDP-1-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
   1920x1080     60.00 +  59.97*   59.96    59.93    40.00  
   1680x1050     59.95    59.88  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1280x800      59.99    59.97    59.81    59.91  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   640x400       59.88    59.98  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1-1 disconnected (normal left inverted right x axis y axis)
HDMI-1-1 disconnected (normal left inverted right x axis y axis)
  1680x1050 (0x4b) 146.250MHz -HSync +VSync
        h: width  1680 start 1784 end 1960 total 2240 skew    0 clock  65.29KHz
        v: height 1050 start 1053 end 1059 total 1089           clock  59.95Hz
  1280x1024 (0x52) 108.000MHz +HSync +VSync
        h: width  1280 start 1328 end 1440 total 1688 skew    0 clock  63.98KHz
        v: height 1024 start 1025 end 1028 total 1066           clock  60.02Hz
  1280x960 (0x55) 108.000MHz +HSync +VSync
        h: width  1280 start 1376 end 1488 total 1800 skew    0 clock  60.00KHz
        v: height  960 start  961 end  964 total 1000           clock  60.00Hz
  1024x768 (0x63) 65.000MHz -HSync -VSync
        h: width  1024 start 1048 end 1184 total 1344 skew    0 clock  48.36KHz
        v: height  768 start  771 end  777 total  806           clock  60.00Hz
  800x600 (0x72) 40.000MHz +HSync +VSync
        h: width   800 start  840 end  968 total 1056 skew    0 clock  37.88KHz
        v: height  600 start  601 end  605 total  628           clock  60.32Hz
  800x600 (0x73) 36.000MHz +HSync +VSync
        h: width   800 start  824 end  896 total 1024 skew    0 clock  35.16KHz
        v: height  600 start  601 end  603 total  625           clock  56.25Hz
  640x480 (0x7f) 25.175MHz -HSync -VSync
        h: width   640 start  656 end  752 total  800 skew    0 clock  31.47KHz
        v: height  480 start  490 end  492 total  525           clock  59.94Hz


/etc/default/grub
> GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1 resume=/dev/mapper/fedora-swap rd.lvm.lv=fedora/root rd.luks.uuid=luks-151e3dab-b261-4982-8d31-5cbb2731017f rd.lvm.lv=fedora/swap nomodeset rhgb quiet"
GRUB_DISABLE_RECOVERY="true"
GRUB_ENABLE_BLSCFG=true

/etc/X11/xorg.conf
' Section "Files"
	ModulePath	"/opt/nvidia/xorg/modules"
	ModulePath	"/usr/lib64/xorg/modules"
EndSection
## avoid glamor that prevent nvidia driver to load correctly
Section "Module"
	Disable	"glamoregl"
#	Load	"modesetting"
EndSection
## ABI config
Section "ServerFlags"
	Option	"IgnoreABI" "1"
EndSection
Section "ServerLayout"
	Identifier	"layout"
	Screen	0	"nvidia_screen"
	Inactive	"intel"
	Option	"Xinerama" "0"
EndSection
## nvidia xorg conf
Section "Device"
	Identifier	"nvidia"
	Driver	"nvidia"
	BusID		"PCI:1:0:0"
EndSection
Section "Screen"
	Identifier	"nvidia_screen"
	Device	"nvidia"
	Option	"AllowEmptyInitialConfiguration"
	Option	"DPI" "96 x 96"
	Option	"SLI" "Off"
	Option	"UseEDID" "true"
	Option	"Stereo" "0"
EndSection
## intel xorg conf
Section "Device"
	Identifier	"intel"
	Driver	"modesetting"
	BusID	"PCI:0:2:0"
EndSection
Section "Screen"
	Identifier	"intel_screen"
	Device	"intel"
	Option	"AccelMethod"  "sna"
	Option	"TearFree" "True"
	Option	"Tiling" "True"
	Option	"SwapbuffersWait" "True"
	Option	"DRI" "3"
EndSection
'
/etc/log/xorg.0.log (last part. This was very much)
> [   309.485] (**) Video Bus: always reports core events
[   309.485] (**) Option "Device" "/dev/input/event7"
[   309.485] (**) Option "_source" "server/udev"
[   309.487] (II) event7  - Video Bus: is tagged by udev as: Keyboard
[   309.487] (II) event7  - Video Bus: device is a keyboard
[   309.488] (II) event7  - Video Bus: device removed
[   309.504] (**) Option "config_info" "udev:/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/LNXVIDEO:00/input/input8/event7"
[   309.504] (II) XINPUT: Adding extended input device "Video Bus" (type: KEYBOARD, id 8)
[   309.504] (**) Option "xkb_layout" "us"
[   309.504] (**) Option "xkb_variant" "euro"
[   309.507] (II) event7  - Video Bus: is tagged by udev as: Keyboard
[   309.507] (II) event7  - Video Bus: device is a keyboard
[   309.509] (II) config/udev: Adding input device Lid Switch (/dev/input/event0)
[   309.509] (II) No input driver specified, ignoring this device.
[   309.509] (II) This device may have been added with another device file.
[   309.510] (II) config/udev: Adding input device Power Button (/dev/input/event1)
[   309.510] (**) Power Button: Applying InputClass "evdev keyboard catchall"
[   309.510] (**) Power Button: Applying InputClass "libinput keyboard catchall"
[   309.510] (**) Power Button: Applying InputClass "system-keyboard"
[   309.510] (II) Using input driver 'libinput' for 'Power Button'
[   309.510] (**) Power Button: always reports core events
[   309.510] (**) Option "Device" "/dev/input/event1"
[   309.510] (**) Option "_source" "server/udev"
[   309.512] (II) event1  - Power Button: is tagged by udev as: Keyboard
[   309.512] (II) event1  - Power Button: device is a keyboard
[   309.512] (II) event1  - Power Button: device removed
[   309.525] (**) Option "config_info" "udev:/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input1/event1"
[   309.525] (II) XINPUT: Adding extended input device "Power Button" (type: KEYBOARD, id 9)
[   309.525] (**) Option "xkb_layout" "us"
[   309.525] (**) Option "xkb_variant" "euro"
[   309.526] (II) event1  - Power Button: is tagged by udev as: Keyboard
[   309.527] (II) event1  - Power Button: device is a keyboard
[   309.530] (II) config/udev: Adding input device USB Optical Mouse (/dev/input/event4)
[   309.530] (**) USB Optical Mouse: Applying InputClass "evdev pointer catchall"
[   309.530] (**) USB Optical Mouse: Applying InputClass "libinput pointer catchall"
[   309.530] (II) Using input driver 'libinput' for 'USB Optical Mouse'
[   309.530] (**) USB Optical Mouse: always reports core events
[   309.530] (**) Option "Device" "/dev/input/event4"
[   309.530] (**) Option "_source" "server/udev"
[   309.586] (II) event4  - USB Optical Mouse: is tagged by udev as: Mouse
[   309.586] (II) event4  - USB Optical Mouse: device is a pointer
[   309.587] (II) event4  - USB Optical Mouse: device removed
[   309.606] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:1BCF:0007.0001/input/input6/event4"
[   309.606] (II) XINPUT: Adding extended input device "USB Optical Mouse" (type: MOUSE, id 10)
[   309.606] (**) Option "AccelerationScheme" "none"
[   309.606] (**) USB Optical Mouse: (accel) selected scheme none/0
[   309.606] (**) USB Optical Mouse: (accel) acceleration factor: 2.000
[   309.606] (**) USB Optical Mouse: (accel) acceleration threshold: 4
[   309.662] (II) event4  - USB Optical Mouse: is tagged by udev as: Mouse
[   309.663] (II) event4  - USB Optical Mouse: device is a pointer
[   309.664] (II) config/udev: Adding input device USB Optical Mouse (/dev/input/mouse0)
[   309.664] (II) No input driver specified, ignoring this device.
[   309.664] (II) This device may have been added with another device file.
[   309.666] (II) config/udev: Adding input device USB Optical Mouse (/dev/input/event5)
[   309.666] (II) No input driver specified, ignoring this device.
[   309.666] (II) This device may have been added with another device file.
[   309.668] (II) config/udev: Adding input device HP Wide Vision HD Camera: HP Wi (/dev/input/event19)
[   309.668] (**) HP Wide Vision HD Camera: HP Wi: Applying InputClass "evdev keyboard catchall"
[   309.668] (**) HP Wide Vision HD Camera: HP Wi: Applying InputClass "libinput keyboard catchall"
[   309.668] (**) HP Wide Vision HD Camera: HP Wi: Applying InputClass "system-keyboard"
[   309.668] (II) Using input driver 'libinput' for 'HP Wide Vision HD Camera: HP Wi'
[   309.668] (**) HP Wide Vision HD Camera: HP Wi: always reports core events
[   309.668] (**) Option "Device" "/dev/input/event19"
[   309.668] (**) Option "_source" "server/udev"
[   309.671] (II) event19 - HP Wide Vision HD Camera: HP Wi: is tagged by udev as: Keyboard
[   309.671] (II) event19 - HP Wide Vision HD Camera: HP Wi: device is a keyboard
[   309.671] (II) event19 - HP Wide Vision HD Camera: HP Wi: device removed
[   309.694] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5:1.0/input/input23/event19"
[   309.694] (II) XINPUT: Adding extended input device "HP Wide Vision HD Camera: HP Wi" (type: KEYBOARD, id 11)
[   309.694] (**) Option "xkb_layout" "us"
[   309.694] (**) Option "xkb_variant" "euro"
[   309.697] (II) event19 - HP Wide Vision HD Camera: HP Wi: is tagged by udev as: Keyboard
[   309.697] (II) event19 - HP Wide Vision HD Camera: HP Wi: device is a keyboard
[   309.699] (II) config/udev: Adding input device HDA Intel PCH Mic (/dev/input/event6)
[   309.699] (II) No input driver specified, ignoring this device.
[   309.699] (II) This device may have been added with another device file.
[   309.700] (II) config/udev: Adding input device HDA Intel PCH Headphone (/dev/input/event11)
[   309.700] (II) No input driver specified, ignoring this device.
[   309.700] (II) This device may have been added with another device file.
[   309.701] (II) config/udev: Adding input device HDA Intel PCH HDMI/DP,pcm=3 (/dev/input/event12)
[   309.701] (II) No input driver specified, ignoring this device.
[   309.701] (II) This device may have been added with another device file.
[   309.702] (II) config/udev: Adding input device HDA Intel PCH HDMI/DP,pcm=7 (/dev/input/event13)
[   309.702] (II) No input driver specified, ignoring this device.
[   309.702] (II) This device may have been added with another device file.
[   309.703] (II) config/udev: Adding input device HDA Intel PCH HDMI/DP,pcm=8 (/dev/input/event14)
[   309.703] (II) No input driver specified, ignoring this device.
[   309.703] (II) This device may have been added with another device file.
[   309.704] (II) config/udev: Adding input device HDA Intel PCH HDMI/DP,pcm=9 (/dev/input/event15)
[   309.704] (II) No input driver specified, ignoring this device.
[   309.704] (II) This device may have been added with another device file.
[   309.705] (II) config/udev: Adding input device HDA Intel PCH HDMI/DP,pcm=10 (/dev/input/event16)
[   309.705] (II) No input driver specified, ignoring this device.
[   309.705] (II) This device may have been added with another device file.
[   309.706] (II) config/udev: Adding input device Elan Touchpad (/dev/input/event17)
[   309.706] (**) Elan Touchpad: Applying InputClass "evdev touchpad catchall"
[   309.706] (**) Elan Touchpad: Applying InputClass "libinput touchpad catchall"
[   309.706] (II) Using input driver 'libinput' for 'Elan Touchpad'
[   309.706] (**) Elan Touchpad: always reports core events
[   309.706] (**) Option "Device" "/dev/input/event17"
[   309.706] (**) Option "_source" "server/udev"
[   309.709] (II) event17 - Elan Touchpad: is tagged by udev as: Touchpad
[   309.712] (II) event17 - Elan Touchpad: device is a touchpad
[   309.712] (II) event17 - Elan Touchpad: device removed
[   309.733] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:1f.4/i2c-6/6-0015/input/input22/event17"
[   309.733] (II) XINPUT: Adding extended input device "Elan Touchpad" (type: TOUCHPAD, id 12)
[   309.735] (**) Option "AccelerationScheme" "none"
[   309.735] (**) Elan Touchpad: (accel) selected scheme none/0
[   309.735] (**) Elan Touchpad: (accel) acceleration factor: 2.000
[   309.735] (**) Elan Touchpad: (accel) acceleration threshold: 4
[   309.738] (II) event17 - Elan Touchpad: is tagged by udev as: Touchpad
[   309.741] (II) event17 - Elan Touchpad: device is a touchpad
[   309.742] (II) config/udev: Adding input device Elan Touchpad (/dev/input/mouse1)
[   309.742] (II) No input driver specified, ignoring this device.
[   309.742] (II) This device may have been added with another device file.
[   309.744] (II) config/udev: Adding input device AT Translated Set 2 keyboard (/dev/input/event3)
[   309.744] (**) AT Translated Set 2 keyboard: Applying InputClass "evdev keyboard catchall"
[   309.744] (**) AT Translated Set 2 keyboard: Applying InputClass "libinput keyboard catchall"
[   309.744] (**) AT Translated Set 2 keyboard: Applying InputClass "system-keyboard"
[   309.744] (II) Using input driver 'libinput' for 'AT Translated Set 2 keyboard'
[   309.744] (**) AT Translated Set 2 keyboard: always reports core events
[   309.744] (**) Option "Device" "/dev/input/event3"
[   309.744] (**) Option "_source" "server/udev"
[   309.746] (II) event3  - AT Translated Set 2 keyboard: is tagged by udev as: Keyboard
[   309.747] (II) event3  - AT Translated Set 2 keyboard: device is a keyboard
[   309.748] (II) event3  - AT Translated Set 2 keyboard: device removed
[   309.757] (**) Option "config_info" "udev:/sys/devices/platform/i8042/serio0/input/input3/event3"
[   309.757] (II) XINPUT: Adding extended input device "AT Translated Set 2 keyboard" (type: KEYBOARD, id 13)
[   309.757] (**) Option "xkb_layout" "us"
[   309.757] (**) Option "xkb_variant" "euro"
[   309.760] (II) event3  - AT Translated Set 2 keyboard: is tagged by udev as: Keyboard
[   309.760] (II) event3  - AT Translated Set 2 keyboard: device is a keyboard
[   309.763] (II) config/udev: Adding input device ST LIS3LV02DL Accelerometer (/dev/input/event10)
[   309.763] (II) No input driver specified, ignoring this device.
[   309.763] (II) This device may have been added with another device file.
[   309.764] (II) config/udev: Adding input device ST LIS3LV02DL Accelerometer (/dev/input/js0)
[   309.764] (II) No input driver specified, ignoring this device.
[   309.764] (II) This device may have been added with another device file.
[   309.770] (II) config/udev: Adding input device HP Wireless hotkeys (/dev/input/event9)
[   309.770] (**) HP Wireless hotkeys: Applying InputClass "evdev keyboard catchall"
[   309.770] (**) HP Wireless hotkeys: Applying InputClass "libinput keyboard catchall"
[   309.770] (**) HP Wireless hotkeys: Applying InputClass "system-keyboard"
[   309.770] (II) Using input driver 'libinput' for 'HP Wireless hotkeys'
[   309.770] (**) HP Wireless hotkeys: always reports core events
[   309.770] (**) Option "Device" "/dev/input/event9"
[   309.770] (**) Option "_source" "server/udev"
[   309.772] (II) event9  - HP Wireless hotkeys: is tagged by udev as: Keyboard
[   309.772] (II) event9  - HP Wireless hotkeys: device is a keyboard
[   309.772] (II) event9  - HP Wireless hotkeys: device removed
[   309.792] (**) Option "config_info" "udev:/sys/devices/virtual/input/input10/event9"
[   309.792] (II) XINPUT: Adding extended input device "HP Wireless hotkeys" (type: KEYBOARD, id 14)
[   309.792] (**) Option "xkb_layout" "us"
[   309.792] (**) Option "xkb_variant" "euro"
[   309.794] (II) event9  - HP Wireless hotkeys: is tagged by udev as: Keyboard
[   309.794] (II) event9  - HP Wireless hotkeys: device is a keyboard
[   309.795] (II) config/udev: Adding input device HP WMI hotkeys (/dev/input/event18)
[   309.795] (**) HP WMI hotkeys: Applying InputClass "evdev keyboard catchall"
[   309.795] (**) HP WMI hotkeys: Applying InputClass "libinput keyboard catchall"
[   309.795] (**) HP WMI hotkeys: Applying InputClass "system-keyboard"
[   309.795] (II) Using input driver 'libinput' for 'HP WMI hotkeys'
[   309.795] (**) HP WMI hotkeys: always reports core events
[   309.795] (**) Option "Device" "/dev/input/event18"
[   309.795] (**) Option "_source" "server/udev"
[   309.797] (II) event18 - HP WMI hotkeys: is tagged by udev as: Keyboard Switch
[   309.797] (II) event18 - HP WMI hotkeys: device is a keyboard
[   309.797] (II) event18 - HP WMI hotkeys: device removed
[   309.822] (**) Option "config_info" "udev:/sys/devices/virtual/input/input14/event18"
[   309.822] (II) XINPUT: Adding extended input device "HP WMI hotkeys" (type: KEYBOARD, id 15)
[   309.822] (**) Option "xkb_layout" "us"
[   309.822] (**) Option "xkb_variant" "euro"
[   309.824] (II) event18 - HP WMI hotkeys: is tagged by udev as: Keyboard Switch
[   309.824] (II) event18 - HP WMI hotkeys: device is a keyboard
[   314.244] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   314.244] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   314.244] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   314.244] (--) NVIDIA(GPU-0): 
[   314.274] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   314.274] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   314.274] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   314.274] (--) NVIDIA(GPU-0): 
[   323.272] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   323.272] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   323.272] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   323.272] (--) NVIDIA(GPU-0): 
[   323.302] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   323.302] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   323.302] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   323.302] (--) NVIDIA(GPU-0): 
[   323.552] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   323.552] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   323.552] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   323.552] (--) NVIDIA(GPU-0): 
[   323.582] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   323.582] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   323.582] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   323.582] (--) NVIDIA(GPU-0): 
[   323.633] (II) NVIDIA(0): Setting mode "HDMI-0: nvidia-auto-select @1920x1080 +1920+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0}"
[   323.944] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   323.944] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   323.944] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   323.944] (--) NVIDIA(GPU-0): 
[   323.974] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   323.974] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   323.974] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   323.974] (--) NVIDIA(GPU-0): 
[   324.440] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   324.440] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   324.440] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   324.440] (--) NVIDIA(GPU-0): 
[   324.470] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   324.470] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   324.470] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   324.470] (--) NVIDIA(GPU-0): 
[   389.218] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   389.218] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   389.218] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   389.218] (--) NVIDIA(GPU-0): 
[   389.248] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   389.248] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   389.248] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   389.248] (--) NVIDIA(GPU-0): 
[   451.936] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   451.936] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   451.936] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   451.937] (--) NVIDIA(GPU-0): 
[   451.967] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   451.967] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   451.967] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   451.967] (--) NVIDIA(GPU-0): 
[   456.482] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   456.482] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   456.482] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   456.482] (--) NVIDIA(GPU-0): 
[   456.512] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   456.512] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   456.512] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   456.512] (--) NVIDIA(GPU-0): 
[   466.458] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   466.458] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   466.458] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   466.458] (--) NVIDIA(GPU-0): 
[   466.489] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): connected
[   466.489] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): Internal TMDS
[   466.489] (--) NVIDIA(GPU-0): AOC 24B1W (DFP-0): 600.0 MHz maximum pixel clock
[   466.489] (--) NVIDIA(GPU-0): 

lspci -mm | grep -i nvidia
> 01:00.0 "VGA compatible controller" "NVIDIA Corporation" "GP107M [GeForce GTX 1050 Ti Mobile]" -ra1 "Hewlett-Packard Company" "Device 8478"

**Comment by wildtruc** [comment]
Ok.
1/ do for xorg file:
```cat /var/log/Xorg.0.log > xorg.log```
and paste the file in your answer.
2/ do : ```xrandr --current | grep "connected"``` for Intel and nvidia.
3/ do : ```cat /etc/nvidia-prime/display.prime``` to see what is define by nps to xrandr for DM. 
4/ your grub conf is wrong, you have:
```rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1``` + ```nomodeset```.
you should have:
```nouveau.modeset=0 rd.driver.blacklist=nouveau``` without nomodset.
**nomodset** option, might be useless and maybe critical, remove it.
**nvidia-drm.modeset=1** is also optional, remove it too at this point.

Your issue mades me working on a code review for grub and xrandr, I will push it on GIT shortly. For now you need to try to fix grub conf and see what's happening (open it as root user or admin). Install **mc** (midnight-commander) if you don't already have it. It will make you "terminal" life easiest.

**Comment by Jay-Aberlour** [comment]
Sorry for late reaction. I had some stuff going on. 
This whole ordeal with the driver (and some other stuff) have made me switch to debian-stable. There the same problem happened, but I found a clue on the debian wiki. One thing lead to another and I solved the issue. The thing is (at least for this debian-version, can't confirm it for Fedora) that the greeter uses a script located at /etc/nvidia-prime/xinitrc.prime. To be honest, I have no idea what made this script. It is basically an if-statement, with what to do if the hdmi is plugged in. The problem lies with that is only does that with the hdmi. I removed the if and left the actual statement and now it works fine in both states.
Thank you for your time and effort @wildtruc

**Comment by wildtruc** [comment]
Nice to ear.
new version of the script, is managing better xinitrc.prime. In fact, the main move of xinitrc.prime is to define the default xrandr for first start. Once did, and user desktop properly configured with user display manager, xrandr use monitor.xml file and overwrite xinitrc.prime rules.
In some case it could confuse the display manager at the first install start, I hope i fixed this now.
