### ISSUE TITLE
xorg.offload.conf not found

### ISSUE THREAD

**Issue by jtreminio** [wildtruc/nvidia-prime-select#14]
This commit https://github.com/wildtruc/nvidia-prime-select/commit/ab8388c0ae2300ffb60c54d352c9a224659ecaca#diff-b67911656ef5d18c4ae36cb6741b7965R14 included reference to `xorg.offload.conf` but this file is not included in repo, nor generated at runtime.

```$ sudo make install
mkdir -p /etc/nvidia-prime
install -Dm755 -t /usr/bin/ nvidia-prime-ui
install -Dm755 -t /usr/sbin/ nvidia-prime-select
install -Dm644 -t /etc/nvidia-prime/ xorg.nvidia.conf
install -Dm644 -t /etc/nvidia-prime/ xorg.offload.conf
install: cannot stat 'xorg.offload.conf': No such file or directory
make: *** [Makefile:14: install] Error 1
```

**Comment by wildtruc** [comment]
Ouch ! did I ?
It was only a preparation for offload, I was supposed to upload the xorg file with it. It look like I forgot a little thing.
I push the xorg file right now.
... and my apologies.
Remind this is only in test for the moment and useful only for people with recent optimus device and willing to put the hand in the mud.

**Comment by wildtruc** [comment]
Done.
