### ISSUE TITLE
Solus Linux - Not switching

### ISSUE THREAD

**Issue by JeffLabonte** [wildtruc/nvidia-prime-select#3]
Hi, 
<br />
<br />I would like to use your script but it doesn't switch cards for me. I might need your help to figure out what is up.
<br />
<br />This is the ouput I get when I do : 
<br />
<br />> sudo nvidia-prime-select intel
<br />
<br />``
<br />cat: /boot/grub2/grub.cfg: No such file or directory
<br />cat: /boot/grub2/grub.cfg: No such file or directory
<br />sed: can't read /boot/grub2/grub.cfg: No such file or directory
<br />``
<br />

**Comment by JeffLabonte** [comment]
In the meantime, I switched to Solus. But still I have tried your command.
``
+ set -e
+ [[ 1000 -ne 0 ]]
+ printf 'Script must be executed as root or sudo :\n'
Script must be executed as root or sudo :
+ exit 1
``

**Comment by wildtruc** [comment]
You run the script in none root user.

Find the nvidia-prime-ui in menu > system > settings. And launch it
from there.

**Comment by wildtruc** [comment]
yes, there is.
Use `bash -x nvidia-prime-select intel`, and copy the result in file and attach it here.

**Comment by JeffLabonte** [comment]
> + set -e
+ [[ 0 -ne 0 ]]
+ install_dir=/etc/nvidia-prime
+ nvidia32_lib_file=/etc/ld.so.conf.d/nvidia-lib32.conf
+ nvidia64_lib_file=/etc/ld.so.conf.d/nvidia-lib64.conf
+ conf=intel
+ nv_drv_32=/usr/lib/nvidia
+ nv_drv_64=/usr/lib64/nvidia
+ nv_xorg_path=/usr/lib64/nvidia/xorg
+ '[' -s /etc/nvidia-prime/library.conf ']'
++ cat /etc/nvidia-prime/library.conf
++ sed -En 's/^(.*)='\''(.*)'\''$/\2/g;p'
++ grep -c .
+ '[' 0 -gt 0 ']'
+ grub_config
++ uname -r
+ boot_key=/boot/vmlinuz-4.15.17-65.current
++ cat /boot/grub2/grub.cfg
++ egrep -c '^.*/boot/vmlinuz-4.15.17-65.current.*nvidia-drm.modeset=1.*$'
cat: /boot/grub2/grub.cfg: No such file or directory
+ '[' 0 -eq 0 ']'
++ cat /boot/grub2/grub.cfg
++ egrep -c '^.*/boot/vmlinuz-4.15.17-65.current.*blacklist=nouveau.*$'
cat: /boot/grub2/grub.cfg: No such file or directory
+ '[' 0 -eq 0 ']'
+ blacklist=' nouveau.modeset=0 rd.driver.blacklist=nouveau'
+ modset='nvidia-drm.modeset=1 nouveau.modeset=0 rd.driver.blacklist=nouveau'
+ [[ -s /etc/modprobe.d/blacklist-nouveau.conf ]]
+ echo 'blacklist nouveau'
nvidia-prime-select: line 60: /etc/modprobe.d/blacklist-nouveau.conf: No such file or directory


that is what I am getting on Solus. /etc/modprobe.d doesn't exists on Solus BTW

**Comment by JeffLabonte** [comment]
> + set -e
> + [[ 0 -ne 0 ]]
> + install_dir=/etc/nvidia-prime
> + nvidia32_lib_file=/etc/ld.so.conf.d/nvidia-lib32.conf
> + nvidia64_lib_file=/etc/ld.so.conf.d/nvidia-lib64.conf
> + conf=intel
> + nv_drv_32=/usr/lib/nvidia
> + nv_drv_64=/usr/lib64/nvidia
> + nv_xorg_path=/usr/lib64/nvidia/xorg
> + '[' -s /etc/nvidia-prime/library.conf ']'
> ++ sed -En 's/^(.*)='\''(.*)'\''$/\2/g;p'
> ++ grep -c .
> ++ cat /etc/nvidia-prime/library.conf
> + '[' 0 -gt 0 ']'
> + grub_config
> ++ uname -r
> + boot_key=/boot/vmlinuz-4.15.17-65.current
> ++ cat /boot/grub2/grub.cfg
> ++ egrep -c '^.*/boot/vmlinuz-4.15.17-65.current.*nvidia-drm.modeset=1.*$'
> cat: /boot/grub2/grub.cfg: No such file or directory
> + '[' 0 -eq 0 ']'
> ++ cat /boot/grub2/grub.cfg
> ++ egrep -c '^.*/boot/vmlinuz-4.15.17-65.current.*blacklist=nouveau.*$'
> cat: /boot/grub2/grub.cfg: No such file or directory
> + '[' 0 -eq 0 ']'
> + blacklist=' nouveau.modeset=0 rd.driver.blacklist=nouveau'
> + modset='nvidia-drm.modeset=1 nouveau.modeset=0 rd.driver.blacklist=nouveau'
> + [[ -s /etc/modprobe.d/blacklist-nouveau.conf ]]
> + sed -Eni -e 's|(linux.*/boot/vmlinuz-4.15.17-65.current.*ro)(.*)$|\1 nvidia-drm.modeset=1 nouveau.modeset=0 rd.driver.blacklist=nouveau \2|g;p' /boot/grub2/grub.cfg
> sed: can't read /boot/grub2/grub.cfg: No such file or directory
>

**Comment by wildtruc** [comment]
ok, I got it.
Apparently Solus don't put usual grub path, or have no grub at all.
Try `find /boot /etc -iname "*grub*"`, you will probably need su right for this, because grub is not user readable. 

I've just write a report sample, if you can feed it, it would be very useful:
### Main:
**distro**: `cat /proc/version`. Help to get distro name and get a tip for possible per distro auto conf.

**session-manager**:

**grub.cfg**: default menuentry 'linux/linux16' whole line. As su or sudo -S prompt, `cat /boot/grub2/grub.cfg| grep "linux.*$(uname -r)"`.

**xrandr providers**: `xrandr --listproviders`, respectively under intel, then nvidia device (if can be started).
 - intel:
 - nvidia:

**xrandr displays**: `xrandr --query`
 - intel:
 - nvidia:

### Optional:
**xorg log**: `cat /var/log/Xorg.0.log`

**lsmod**: to get intel, nvidia, bbswitch (if any) loaded modules. `lsmod | grep "nvidia\|bbswitch\|intel"`

**Comment by JeffLabonte** [comment]
Solus doesn't use grub at all when using UEFI. I will post you a report using your sample.

**Comment by wildtruc** [comment]
Ok, all looks fine, but...
How did you get on NVIDIA-0 provider in first place?
Is it whith nvidia-prime-select or an other tool or manual configuration?

For boot options, I'm not familiar with UEFI boot code (iI've none), need to seek deeper.

What's return:
`cat /etc/nvidia-prime/xinitrc.prime`
`cat /etc/nvidia-prime/display.prime`
`ls -l /etc/X11/xorg.conf`

I've just upload fixes allowing to unset grub detection and configuration.
Use the GUI tool to not allow grub part, is really easier.

**Comment by JeffLabonte** [comment]
The boot parameters are in /etc/kernel in differents files. Those are the parameter I had;

**Boot Parameters**
resume=UUID=ad3d9f82-f8b0-4af7-96f5-10328f004c2a nouveau.modeset=0 acpi_osi=! acpi_osi='Windows 2009' pcie_port_pm=off

I am a distro hopper and Solus had some serious issues for me during work so I went back to Ubuntu. I hope the info I gave you helped you improve your script a bit more!

**Comment by wildtruc** [comment]
I assume you don't have Solus anymore. Too bad, I seek deeper and I had a few more question about Solus UEFI boot system.
There's maybe a solution for you [there](https://github.com/MarechalLima/Systemd-Nvidia-Entry/releases).

**Comment by JeffLabonte** [comment]
oh nice, thank you. I will look into it!

**Comment by JeffLabonte** [comment]
@wildtruc I got back to Solus and the link the gave me worked. It works like a charm with Solus UEFI system.

**Comment by wildtruc** [comment]
Good!
Well, you're back on Solus. Could you do 2 last thinks?
The result of `xrandr --listproviders` when you are on intel device and a tar.gz of the /mnt directory that will very help me to understand how it works and maybe add it to the script.

**Comment by JeffLabonte** [comment]
This is what comes up when I execute `xrandr --listproviders` : 

> Providers: number : 1
> Provider 0: id: 0x47 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 5 associated providers: 0 name:modesetting
> 

My /mnt folder is empty .... well not anymore, it has an empty folder called Systemd-Nvidia-Entry

**Comment by wildtruc** [comment]
It seems that @TimRichardson was right.
On intel session provider is not intel, but modesetting. I will do some test this WE and see how it goes.
Thanks.
And I wont be shy :)

**Comment by JeffLabonte** [comment]
you are most welcome! happy to help!
