### ISSUE TITLE
sh ./changelog.sh might not work

### ISSUE THREAD

**Issue by 3togo** [wildtruc/nvidia-prime-select#4]
sh ./changelog.sh may not work with "find", better change it to bash
______________________________________________________________________________________________________

diff --git a/Makefile b/Makefile
index cddfe35..708339a 100644
--- a/Makefile
+++ b/Makefile
@@ -37,7 +37,7 @@ update:
        install -Dm644 -t /usr/share/applications/ nvidia-prime-ui.desktop
        install -C -Dm644 -t /usr/share/polkit-1/actions/ com.github.pkexec.nvidia-prime-select.policy
        install -C -Dm644 -t /usr/share/polkit-1/actions/ com.github.pkexec.nvidia-prime-editor.policy
-       sh ./changelog.sh
+       bash ./changelog.sh
 
 uninstall:
        rm -rf $(INSTALL_DIR)
[patch.txt](https://github.com/wildtruc/nvidia-prime-select/files/2136562/patch.txt)

**Comment by wildtruc** [comment]
Thanks.
Merged.
