### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by simbd** [wildtruc/nvidia-prime-select#6]
Hello

Nvidia-prime-select does not work home on Archlinux : when I select the nvidia card then I reboot, it's still the intel chipset of used.

Should you copy "xorg.intel.conf" and "xorg.nvidia.conf" in /etc/xorg.conf.d/ ?
and should you modify his files?

**Comment by wildtruc** [comment]
nvidia-prime-select doesn't use /etcX11/xorg.conf.d, but a link of xorg.conf to /etc/nvidia-prime intel or nvidia xorg file. Issues with Arch are known, but not very well fixed.

Please, use the report.sample from the GIT dir. We will try to figure what went wrong.

**Comment by wildtruc** [comment]
Close on no more threads and too old.
